// Code generated by https://github.com/Miruken-Go/miruken/tools/cmd/mirukentypes; DO NOT EDIT.

package validator

import "github.com/miruken-go/miruken"
import "reflect"

var HandlerTypes = []reflect.Type{
	miruken.TypeOf[*IntegrationValidator](),
}

